### ISSUE TITLE
Expand error happens when using typescript snippet file

### ISSUE THREAD

**Issue by ryoppippi** [uga-rosa/cmp-denippet#1]
Hi!

When I define snippet in typescript, errors happens when expanding or previewing snippet.

Here is the error
```
17:29:39 msg_show Error executing vim.schedule lua callback: function denippet#to_string[1]..<SNR>122_request[4]..denops#request[1]..denops#_internal#server#chan#request[6]..denops#_internal#rpc#nvim#request, line 1: Vim(return):Error invoking 'invoke' on channel 5 (denops):
Error: Failed parsing: 
    at Object.snippetToString (file:///Users/ryoppippi/.local/share/nvim/lazy/denippet.vim/denops/denippet/main.ts:226:15)
    at Plugin.call (file:///Users/ryoppippi/.local/share/nvim/lazy/denops.vim/denops/@denops-private/service.ts:138:45)
    at Service.#dispatch (file:///Users/ryoppippi/.local/share/nvim/lazy/denops.vim/denops/@denops-private/service.ts:68:25)
    at Service.dispatch (file:///Users/ryoppippi/.local/share/nvim/lazy/denops.vim/denops/@denops-private/service.ts:73:34)
    at invoke (file:///Users/ryoppippi/.local/share/nvim/lazy/denops.vim/denops/@denops-private/host.ts:78:22)
    at Object.invoke (file:///Users/ryoppippi/.local/share/nvim/lazy/denops.vim/denops/@denops-private/host/nvim.ts:31:16)
    at dispatch (https://deno.land/x/messagepack_rpc@v2.0.3/dispatcher.ts:36:36)
    at Session.#dispatch (https://deno.land/x/messagepack_rpc@v2.0.3/session.ts:244:28)
    at Session.#handleRequestMessage (https://deno.land/x/messagepack_rpc@v2.0.3/session.ts:271:53)
    at Session.#handleMessage (https://deno.land/x/messagepack_rpc@v2.0.3/session.ts:255:37)
stack traceback:
	[C]: in function 'denippet#to_string'
	....local/share/nvim/lazy/cmp-denippet/lua/cmp_denippet.lua:41: in function 'resolve'
	...pippi/.local/share/nvim/lazy/nvim-cmp/lua/cmp/source.lua:384: in function 'resolve'
	...ppippi/.local/share/nvim/lazy/nvim-cmp/lua/cmp/entry.lua:505: in function 'resolve'
	...oppippi/.local/share/nvim/lazy/nvim-cmp/lua/cmp/view.lua:287: in function 'fn'
	.../.local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/async.lua:71: in function <.../.local/share/nvim/lazy/nvim-cmp/lua/cmp/utils/async.lua:69>

```

snippet file
```ts
import { type TSSnippet } from "https://deno.land/x/denippet_vim@v0.5.5/loader.ts";

export const snippets: Record<string, TSSnippet> = {
  "as const satisfies": {
    prefix: "acs",
    description: "as const satisfies",
    body: "as const satisfies $0",
  },
};

```

**Comment by ryoppippi** [comment]
I found that the body from the function `vim.fn["denippet#get_complete_items"]` is empty when snippets defined in typescript

**Comment by uga-rosa** [comment]
I think because body is a typescript function, it will be empty when passed to Vim. I'll check more later.

**Comment by ryoppippi** [comment]
Thanks!!
